<?php
// Register custom post types
// Register Custom Post Type

	$labels = array(
		'name'                  => _x( 'Galleries', 'Post Type General Name', 'wptitaaurings' ),
		'singular_name'         => _x( 'Gallery', 'Post Type Singular Name', 'wptitaaurings' ),
		'menu_name'             => __( 'Gallery', 'wptitaaurings' ),
		'name_admin_bar'        => __( 'Gallery', 'wptitaaurings' ),
		'archives'              => __( 'Gallery Archives', 'wptitaaurings' ),
		'attributes'            => __( 'Gallery Attributes', 'wptitaaurings' ),
		'parent_item_colon'     => __( 'Parent Item:', 'wptitaaurings' ),
		'all_items'             => __( 'All Items', 'wptitaaurings' ),
		'add_new_item'          => __( 'Add New Item', 'wptitaaurings' ),
		'add_new'               => __( 'Add New', 'wptitaaurings' ),
		'new_item'              => __( 'New Item', 'wptitaaurings' ),
		'edit_item'             => __( 'Edit Item', 'wptitaaurings' ),
		'update_item'           => __( 'Update Item', 'wptitaaurings' ),
		'view_item'             => __( 'View Item', 'wptitaaurings' ),
		'view_items'            => __( 'View Items', 'wptitaaurings' ),
		'search_items'          => __( 'Search Item', 'wptitaaurings' ),
		'not_found'             => __( 'Not found', 'wptitaaurings' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'wptitaaurings' ),
		'featured_image'        => __( 'Featured Image', 'wptitaaurings' ),
		'set_featured_image'    => __( 'Set featured image', 'wptitaaurings' ),
		'remove_featured_image' => __( 'Remove featured image', 'wptitaaurings' ),
		'use_featured_image'    => __( 'Use as featured image', 'wptitaaurings' ),
		'insert_into_item'      => __( 'Insert into item', 'wptitaaurings' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'wptitaaurings' ),
		'items_list'            => __( 'Items list', 'wptitaaurings' ),
		'items_list_navigation' => __( 'Items list navigation', 'wptitaaurings' ),
		'filter_items_list'     => __( 'Filter items list', 'wptitaaurings' ),
	);
	$args = array(
		'label'                 => __( 'Gallery', 'wptitaaurings' ),
		'description'           => __( 'Add galleries here', 'wptitaaurings' ),
		'labels'                => $labels,
		'supports'              => array( 'title' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'							=> 'dashicons-images-alt',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'gallery', $args );


	$labels2 = array(
		'name'                  => _x( 'Business Workshops', 'Post Type General Name', 'wptitaaurings' ),
		'singular_name'         => _x( 'Business Workshop', 'Post Type Singular Name', 'wptitaaurings' ),
		'menu_name'             => __( 'Business Workshops', 'wptitaaurings' ),
		'name_admin_bar'        => __( 'Business Workshops', 'wptitaaurings' ),
		'archives'              => __( 'Business Workshop Archives', 'wptitaaurings' ),
		'attributes'            => __( 'Business Workshop Attributes', 'wptitaaurings' ),
		'parent_item_colon'     => __( 'Parent Item:', 'wptitaaurings' ),
		'all_items'             => __( 'All Items', 'wptitaaurings' ),
		'add_new_item'          => __( 'Add New Item', 'wptitaaurings' ),
		'add_new'               => __( 'Add New', 'wptitaaurings' ),
		'new_item'              => __( 'New Item', 'wptitaaurings' ),
		'edit_item'             => __( 'Edit Item', 'wptitaaurings' ),
		'update_item'           => __( 'Update Item', 'wptitaaurings' ),
		'view_item'             => __( 'View Item', 'wptitaaurings' ),
		'view_items'            => __( 'View Items', 'wptitaaurings' ),
		'search_items'          => __( 'Search Item', 'wptitaaurings' ),
		'not_found'             => __( 'Not found', 'wptitaaurings' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'wptitaaurings' ),
		'featured_image'        => __( 'Featured Image', 'wptitaaurings' ),
		'set_featured_image'    => __( 'Set featured image', 'wptitaaurings' ),
		'remove_featured_image' => __( 'Remove featured image', 'wptitaaurings' ),
		'use_featured_image'    => __( 'Use as featured image', 'wptitaaurings' ),
		'insert_into_item'      => __( 'Insert into item', 'wptitaaurings' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'wptitaaurings' ),
		'items_list'            => __( 'Items list', 'wptitaaurings' ),
		'items_list_navigation' => __( 'Items list navigation', 'wptitaaurings' ),
		'filter_items_list'     => __( 'Filter items list', 'wptitaaurings' ),
	);
	$args2 = array(
		'label'                 => __( 'Business Workshops', 'wptitaaurings' ),
		'description'           => __( 'Add workshops here', 'wptitaaurings' ),
		'labels'                => $labels2,
		'supports'              => array( 'title' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'							=> 'dashicons-businessman',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'business-workshops', $args2 );